name: jmas_movil
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  http: ^1.2.2 #WEB
  shared_preferences: ^2.3.3 #Guardar token
  intl: ^0.19.0 #Fecha
  pdf: ^3.11.1 #PDF
  printing: ^5.13.4 #Imprimir
  path_provider: ^2.1.5 #Archivos sistema
  file_picker: ^8.1.6 #Seleccionar carpeta
  permission_handler: ^10.0.0 #Ruta de archivo
  mobile_scanner: ^6.0.2 #Scanner QR/Barras  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0

flutter:  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/sinFoto.jpg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
